name: Validate renovate presets

on:
  push:
    paths:
      - "default.json"
      - ".github/workflows/renovate-validate.yml"
  pull_request:
    paths:
      - "default.json"
      - ".github/workflows/renovate-validate.yml"
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - run: |
          docker run --rm -v \
            "${{ github.workspace }}:/workspace" \
            -w /workspace \
            ghcr.io/renovatebot/renovate:latest \
            renovate-config-validator \
            "default.json"
