name: Update subs

on:
  workflow_dispatch:

jobs:
  update:
    name: Update subs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      subconverter:
        image: asdlokj1qpi23/subconverter:latest@sha256:3e4f48f6ac831cd9882a943eb31435d84499d87b991d7770939e26e6e5803719
        ports:
          - 25500:25500
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Restore history
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ github.workspace }}/output
          key: history
          restore-keys: |
            history

      - name: Replace gist id and token
        uses: mikefarah/yq@1b9b4ac5187171d2e5e3129be0cfa827c7f9d53d # v4.53.3
        with:
          cmd: yq -i '."github-gist-id" = "${{ secrets.GIST_ID }}" | ."github-token" = "${{ secrets.GH_PAT }}"' config/config.yaml

      - name: Update subs
        run: |
          mkdir -p output
          docker run --rm \
            --init \
            --network host \
            -v ./config:/app/config \
            -v ./output:/app/output \
            ghcr.io/sinspired/subs-check-pro:latest || true
          sudo chown -R $(id -u):$(id -g) ./output

      - name: Save history
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ github.workspace }}/output
          key: history-${{ github.run_id }}
