name: Update subs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Restore history
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ${{ github.workspace }}/output/history
          key: history
          restore-keys: |
            history

      - name: Replace gist id and token
        uses: mikefarah/yq@1b9b4ac5187171d2e5e3129be0cfa827c7f9d53d # v4.53.3
        with:
          cmd: yq -i '."github-gist-id" = "${{ secrets.GIST_ID }}" | ."github-token" = "${{ secrets.GH_PAT }}"' config/config.yaml

      - name: Update subs
        run: |
          docker run -d \
            --name subs-check-pro \
            -p 8299:8299 \
            -p 8199:8199 \
            -v ./config:/app/config \
            -v ./output:/app/output \
            ghcr.io/sinspired/subs-check-pro:latest || true

      - name: Save history
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ${{ github.workspace }}/output
          key: history-${{ github.run_id }}
