name: Update subs

on:
  workflow_dispatch:

jobs:
  update:
    name: Update subs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      subconverter:
        image: asdlokj1qpi23/subconverter:latest@sha256:3e4f48f6ac831cd9882a943eb31435d84499d87b991d7770939e26e6e5803719
        ports:
          - 25500:25500
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: subs

      - name: Update subs
        run: |
          mkdir -p output
          docker run --rm \
            --init \
            --network host \
            -v ./config:/app/config \
            -v ./output:/app/output \
            ghcr.io/sinspired/subs-check-pro:latest || true
          sudo chown -R $(id -u):$(id -g) ./output

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: subs
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          force_orphan: true
          enable_jekyll: true
